- name: setup mysql for expence
  hosts: all
  become: yes
  tasks:
    - name: disable nodejs default version
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: enable nodejs 18 version
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: copy backend service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: aad application user
      ansible.builtin.user:
        name: expense
    - name: delete old app dir
      ansible.builtin.file:
        path: /app
        state: absent
    - name: create app dir
      ansible.builtin.file:
        path: /app
        state: directory
    - name: download and extract
      ansible.builtin.unarchive:
        remote_src: yes
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
    - name: Download NodeJs Dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: Load Schema
      ansible.builtin.shell: mysql - h backend-dev.nagarajuchinni.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql
    - name: start backend
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes

